"""Versioned human-acceptance specification for the staged Getfit rebuild."""

from typing import Any

SPEC_VERSION = "2026-10-02-v1"


def _criterion(
    criterion_id: str,
    title: str,
    expected: str,
    test_steps: list[str],
    *,
    source: str,
    route: str,
    viewports: list[str] | None = None,
    mandatory: bool = True,
    automated_check: str | None = None,
) -> dict[str, Any]:
    return {
        "criterion_id": criterion_id,
        "title": title,
        "expected": expected,
        "test_steps": test_steps,
        "source": source,
        "route": route,
        "viewports": viewports or ["phone", "tablet", "desktop"],
        "mandatory": mandatory,
        "automated_check": automated_check,
    }


ACCEPTANCE_SPEC: dict[str, Any] = {
    "spec_version": SPEC_VERSION,
    "title": "Getfit staged product acceptance",
    "status_values": ["NOT_TESTED", "PASS", "FAIL", "BLOCKED"],
    "rules": {
        "gate_pass": "Every mandatory human criterion must be PASS and required automated checks must pass.",
        "gate_fail": "Any mandatory FAIL makes the gate FAIL until corrected and re-tested.",
        "blocked": "Use BLOCKED when a prerequisite state cannot be reached; blocked criteria do not count as passed.",
        "version_scope": "Acceptance results are scoped to app version and specification version.",
    },
    "gates": [
        {
            "gate_id": "GATE-1-TODAY",
            "title": "Today / Home",
            "description": "Approved Home Dashboard and Workout Selection surfaces.",
            "source": "Approved design board panels 4–5 + Week 1 programme authority",
            "criteria": [
                _criterion(
                    "TODAY-01",
                    "Two-surface product composition",
                    "Today presents one cohesive dark coaching dashboard beside/before one light Week 1 workout-selection surface; it must not read as a collection of generic admin cards.",
                    [
                        "Open Today.",
                        "Compare the coaching dashboard and workout-selection composition with the approved board.",
                        "Check that secondary context does not compete with the two primary surfaces.",
                    ],
                    source="Approved design board panels 4–5",
                    route="/",
                ),
                _criterion(
                    "TODAY-02",
                    "Trusted identity and personal presentation",
                    "The resolved person is clearly shown without any browser-side person selector or internal identity terminology.",
                    [
                        "Confirm the signed-in person is Kris for the current Home Assistant user.",
                        "Confirm no person picker, person ID or cross-system ID is visible.",
                    ],
                    source="Trusted Home Assistant identity contract + design board",
                    route="/",
                    automated_check="identity-selector rejection and person-scoped route tests",
                ),
                _criterion(
                    "TODAY-03",
                    "Next workout authority",
                    "Next Workout shows the approved Week/Day, workout title and approved duration without inventing later programme content.",
                    [
                        "Confirm Week 1 · Day 1 when no workout is completed.",
                        "Confirm Upper Body + Bike.",
                        "Confirm approved duration presentation.",
                    ],
                    source="Week 1 programme seed + design board",
                    route="/",
                    automated_check="Today programme-position integration tests",
                ),
                _criterion(
                    "TODAY-04",
                    "Start and Resume action",
                    "The primary action is obvious, starts a draft, enters the workout player, and changes to Resume when a draft exists.",
                    [
                        "Press Start Workout.",
                        "Confirm the Workout page opens with an active draft.",
                        "Leave the workout and return to Today.",
                        "Confirm the action becomes Resume Workout and resumes the same draft.",
                    ],
                    source="Workout draft lifecycle contract",
                    route="/",
                    viewports=["phone", "tablet"],
                    automated_check="full training journey draft/start/resume tests",
                ),
                _criterion(
                    "TODAY-05",
                    "Current prescription snapshot",
                    "The Home snapshot shows real approved person-specific targets. Kris Day 1 includes Floor press 6 kg each, Row 10 kg and Shoulder press 5 kg each; unapproved person loads are never fabricated.",
                    [
                        "Check the three current target rows.",
                        "Compare the values with Week 1 person overrides.",
                        "Confirm no guessed values appear for a person without approved overrides.",
                    ],
                    source="Week 1 person overrides",
                    route="/",
                    automated_check="Home dashboard authority tests",
                ),
                _criterion(
                    "TODAY-06",
                    "Weekly status and cardio evidence",
                    "This Week, Last Workout and Weekly Cardio use completed workout evidence and do not fabricate completions.",
                    [
                        "Check four Week 1 status indicators.",
                        "Check Last Workout against actual history.",
                        "Check weekly cardio minutes against completed cardio evidence.",
                    ],
                    source="Workout evidence read models + design board",
                    route="/",
                    automated_check="history and weekly-cardio read-model tests",
                ),
                _criterion(
                    "TODAY-07",
                    "Weekly goal",
                    "The Weekly Goal clearly presents 150 minutes moderate activity plus 2–4 strength sessions and current evidence-based progress.",
                    [
                        "Locate the Weekly Goal panel.",
                        "Confirm 150-minute goal and 2–4 strength-session guidance.",
                        "Confirm displayed progress agrees with completed workout evidence.",
                    ],
                    source="Approved design board",
                    route="/",
                ),
                _criterion(
                    "TODAY-08",
                    "Responsive product quality",
                    "Today remains visually coherent at phone, tablet and desktop sizes with readable hierarchy, touch-sized controls and no internal/debug content.",
                    [
                        "Review phone, tablet and desktop captures.",
                        "Check for clipping, excessive dead space, tiny text, awkward stacking or duplicated controls.",
                        "Confirm no internal IDs or debug language are visible.",
                    ],
                    source="Approved responsive product direction",
                    route="/",
                    automated_check="responsive touch and implementation-ID tests",
                ),
            ],
        },
        {
            "gate_id": "GATE-2-STRENGTH",
            "title": "Strength workout player",
            "description": "Active Day 1 strength coaching, set completion and rest flow.",
            "source": "Approved design board panels 6–7 + Week 1 Day 1 authority",
            "criteria": [
                _criterion(
                    "STRENGTH-01",
                    "Active workout state",
                    "An active Day 1 draft renders the strength player rather than the empty Workout state.",
                    ["Start or resume Day 1.", "Open Workout.", "Confirm an active exercise is visible."],
                    source="Workout draft lifecycle",
                    route="/workout",
                    automated_check="review-pack active/empty state detection",
                ),
                _criterion(
                    "STRENGTH-02",
                    "Current exercise hierarchy",
                    "Dumbbell Floor Press is the dominant current exercise with clear exercise count and workout progress.",
                    ["Open the first strength stage.", "Confirm Floor Press dominates the page.", "Confirm exercise/set progress is understandable at a glance."],
                    source="Approved design board panel 6",
                    route="/workout",
                ),
                _criterion(
                    "STRENGTH-03",
                    "Prescribed target metrics",
                    "The current Floor Press prominently shows 10 reps, 6 kg each and prescribed 2-second eccentric / 1-second concentric tempo.",
                    ["Compare reps, load and tempo with Week 1 authority.", "Confirm target values are visually primary and actual-entry fields are secondary."],
                    source="Week 1 Day 1 programme authority + design board",
                    route="/workout",
                    automated_check="player-context prescription tests",
                ),
                _criterion(
                    "STRENGTH-04",
                    "Complete Set primary action",
                    "Complete Set is the obvious action for the current set and does not get lost among secondary navigation controls.",
                    ["Locate the primary set action without scrolling where practical.", "Complete Set 1."],
                    source="Approved design board panel 6",
                    route="/workout",
                ),
                _criterion(
                    "STRENGTH-05",
                    "Actual performance recording",
                    "Actual reps/load and effort can be recorded without making the workout player look like a database form.",
                    ["Record actual reps/load.", "Record RPE/RIR where offered.", "Confirm target and actual values are clearly distinguished."],
                    source="Workout evidence contract",
                    route="/workout",
                ),
                _criterion(
                    "STRENGTH-06",
                    "Set-complete feedback",
                    "After completing a set, a dedicated coaching state offers Too easy, About right, Too hard and Pain/Stop.",
                    ["Complete Floor Press Set 1.", "Confirm all four feedback choices are visible and understandable."],
                    source="Approved design board panel 7",
                    route="/workout",
                ),
                _criterion(
                    "STRENGTH-07",
                    "Rest countdown",
                    "The set-complete state shows a prominent rest countdown driven by the prescribed 75–90 second rest range, with 01:30 acceptable for the board's first-set presentation.",
                    ["Complete Set 1.", "Confirm the countdown is prominent.", "Confirm it does not silently complete the next strength set."],
                    source="Week 1 Day 1 authority + approved design board",
                    route="/workout",
                ),
                _criterion(
                    "STRENGTH-08",
                    "Next set / exercise preview",
                    "The player clearly states what follows the rest period, including next set or next exercise.",
                    ["During rest, find the next-action preview.", "Confirm it agrees with the programme sequence."],
                    source="Approved design board panel 7",
                    route="/workout",
                ),
                _criterion(
                    "STRENGTH-09",
                    "Workout controls",
                    "Previous, Pause/Resume, Skip, Next and Stop are available as secondary controls with safe behaviour.",
                    ["Exercise each control in a disposable draft where safe.", "Confirm Stop saves rather than falsely completing the workout."],
                    source="Workout state-machine contract",
                    route="/workout",
                    automated_check="workout player state tests",
                ),
                _criterion(
                    "STRENGTH-10",
                    "Draft persistence",
                    "Leaving/reloading during a workout preserves the current draft and recorded state without duplicating completion evidence.",
                    ["Record partial set state.", "Reload or leave/re-enter.", "Confirm state resumes correctly."],
                    source="Workout draft and idempotency contracts",
                    route="/workout",
                    automated_check="full training journey and idempotency tests",
                ),
            ],
        },
        {
            "gate_id": "GATE-3-TECHNIQUE",
            "title": "Exercise technique and media",
            "description": "Movement demonstrations and technique coaching.",
            "source": "Approved design board panel 7 + Exercise Library product direction",
            "criteria": [
                _criterion(
                    "TECH-01",
                    "Movement demonstration",
                    "Exercise detail uses approved local movement imagery/animation when available rather than a repeated generic placeholder.",
                    ["Open Floor Press, Goblet Squat and RDL.", "Confirm each has movement-specific visual content."],
                    source="Approved design board + local-media direction",
                    route="/library",
                ),
                _criterion(
                    "TECH-02",
                    "Three-stage technique sequence",
                    "Floor Press supports Start → Lower → Drive Up visual coaching when approved assets exist.",
                    ["Open Floor Press technique.", "Check the three movement phases and labels."],
                    source="Approved design board panel 7",
                    route="/library",
                ),
                _criterion(
                    "TECH-03",
                    "Technique checklist",
                    "Movement-specific technique cues are concise, useful and visually associated with the exercise.",
                    ["Read the technique cues.", "Confirm they apply to the selected movement and are not generic filler."],
                    source="Exercise Library technique authority",
                    route="/library",
                ),
                _criterion(
                    "TECH-04",
                    "Images / Technique / Video hierarchy",
                    "The detail view provides clear Images, Technique and Video access; video appears only where an approved link exists.",
                    ["Open an exercise with media.", "Check each media/technique mode.", "Confirm unavailable video is not fabricated."],
                    source="Approved design board panel 7",
                    route="/library",
                ),
                _criterion(
                    "TECH-05",
                    "Intentional media fallback",
                    "When approved media is unavailable, the fallback is deliberate and movement-specific where possible; it must not present the same generic stick figure as if it were real technique media.",
                    ["Open an exercise without approved media.", "Confirm the fallback is clearly labelled and visually intentional."],
                    source="Media safety/product contract",
                    route="/library",
                ),
            ],
        },
        {
            "gate_id": "GATE-4-CARDIO",
            "title": "Cardio and intervals",
            "description": "Spin bike, treadmill and interval coaching states.",
            "source": "Approved design board panels 8–9 + Week 1 cardio authority",
            "criteria": [
                _criterion(
                    "CARDIO-01",
                    "Spin-bike variable model",
                    "Spin bike uses time, cadence, resistance and RPE only; speed and incline never appear.",
                    ["Open a spin-bike stage.", "Check target and actual fields.", "Confirm no speed or incline control exists."],
                    source="Equipment contract + Week 1 programme",
                    route="/workout",
                    automated_check="bike target presentation tests",
                ),
                _criterion(
                    "CARDIO-02",
                    "Treadmill variable model",
                    "Treadmill uses time, speed, incline and RPE; configured incline capability is capped at 20%.",
                    ["Open a treadmill stage.", "Check fields and limits.", "Confirm bike cadence/resistance fields are absent."],
                    source="Equipment profile + Week 1 programme",
                    route="/workout",
                    automated_check="treadmill target presentation tests",
                ),
                _criterion(
                    "CARDIO-03",
                    "Bike finisher presentation",
                    "Day 1 bike conditioning presents a purpose-built timer with 15:00 duration, 80–90 rpm, moderate resistance and RPE 5.",
                    ["Reach Day 1 bike conditioning.", "Compare all targets with Week 1 authority."],
                    source="Week 1 Day 1 programme + design board panel 8",
                    route="/workout",
                ),
                _criterion(
                    "CARDIO-04",
                    "Hard interval state",
                    "Day 4 hard interval has a distinct high-intensity visual state with 30-second timer, round count, 85–100 rpm and RPE 7–8.",
                    ["Start Day 4 interval stage.", "Check hard-state treatment and targets."],
                    source="Week 1 Day 4 programme + design board panel 9",
                    route="/workout",
                ),
                _criterion(
                    "CARDIO-05",
                    "Recovery interval state",
                    "Recovery clearly transitions to 90 seconds, 60–75 rpm, light resistance and RPE 2–3.",
                    ["Allow/advance hard interval into recovery.", "Check recovery timer and targets."],
                    source="Week 1 Day 4 programme + design board panel 9",
                    route="/workout",
                ),
                _criterion(
                    "CARDIO-06",
                    "Target versus actual",
                    "Prescribed cardio targets and user-recorded actual values are visually distinct and saved without altering programme authority.",
                    ["Record actual cardio values.", "Reload/resume.", "Confirm programme targets remain unchanged."],
                    source="Workout evidence/programme authority contract",
                    route="/workout",
                ),
            ],
        },
        {
            "gate_id": "GATE-5-PROGRESS",
            "title": "Progress",
            "description": "Evidence-based progression and recent training history.",
            "source": "Approved design board panel 10 + performed workout evidence",
            "criteria": [
                _criterion(
                    "PROGRESS-01",
                    "Exercise progression chart",
                    "A real per-exercise progression chart is driven only by performed evidence; no synthetic or future points are drawn.",
                    ["Open Progress after multiple sessions.", "Select/inspect an exercise.", "Compare plotted values with recorded history."],
                    source="Approved design board panel 10 + workout evidence",
                    route="/progress",
                ),
                _criterion(
                    "PROGRESS-02",
                    "Recent progression",
                    "Recent-session progression is readable as a product summary rather than raw event/evidence records.",
                    ["Review recent sessions.", "Confirm date, load/reps and useful progression context are visible.", "Confirm event IDs are hidden."],
                    source="Approved design board panel 10",
                    route="/progress",
                ),
                _criterion(
                    "PROGRESS-03",
                    "Programme completion",
                    "Completed sessions and programme completion reflect actual evidence and approved imported content only.",
                    ["Compare completion count with workout history.", "Confirm no future Week 2+ completion appears."],
                    source="Programme/history read models",
                    route="/progress",
                    automated_check="progress read-model tests",
                ),
                _criterion(
                    "PROGRESS-04",
                    "Person scope",
                    "Progress shows only the trusted resolved person's history.",
                    ["Confirm Kris history is shown for Kris.", "Confirm no browser-side person selector exists."],
                    source="Identity/person-scope contract",
                    route="/progress",
                    automated_check="person-scoped history tests",
                ),
            ],
        },
        {
            "gate_id": "GATE-6-LIBRARY-SETTINGS",
            "title": "Library, Settings and integrations",
            "description": "Consumer-ready supporting product surfaces.",
            "source": "Approved design board + equipment/integration contracts",
            "criteria": [
                _criterion(
                    "LIBRARY-01",
                    "Exercise library cards",
                    "Library cards use movement-specific presentation and useful body-area/movement context; repeated generic placeholders are not accepted as finished media.",
                    ["Browse the library on phone and desktop.", "Compare several different movements.", "Check visual distinction and readability."],
                    source="Exercise Library product direction",
                    route="/library",
                ),
                _criterion(
                    "LIBRARY-02",
                    "Exercise history",
                    "Exercise detail shows the resolved person's relevant recent performance without exposing internal identifiers.",
                    ["Open an exercise with history.", "Check recent performed values.", "Confirm no implementation IDs are visible."],
                    source="Person-scoped exercise history contract",
                    route="/library",
                    automated_check="exercise-history person-scope tests",
                ),
                _criterion(
                    "SETTINGS-01",
                    "Equipment capabilities",
                    "Settings presents treadmill max incline 20%, spin-bike cadence/resistance with no incline, and adjustable dumbbells in consumer language.",
                    ["Open Settings.", "Check each configured equipment capability."],
                    source="Installation equipment profile",
                    route="/settings",
                ),
                _criterion(
                    "SETTINGS-02",
                    "Calibration and progression",
                    "Settings explains calibration and progression without exposing implementation architecture or silently changing prescriptions.",
                    ["Review calibration/progression copy.", "Confirm changes are suggestions/approved actions rather than silent mutation."],
                    source="Approved calibration/progression direction",
                    route="/settings",
                ),
                _criterion(
                    "SETTINGS-03",
                    "Integration status",
                    "Pep Health and Menu-Nutrition statuses are understandable and show only configured/real state; endpoints, tokens and cross-system IDs are hidden.",
                    ["Review integration cards.", "Confirm no endpoint/token/internal ID is visible."],
                    source="External-context integration contract",
                    route="/settings",
                    automated_check="safe settings/status tests",
                ),
            ],
        },
        {
            "gate_id": "GATE-FINAL-REGRESSION",
            "title": "Final product regression",
            "description": "Release-level product, data and Home Assistant regression.",
            "source": "Getfit release gate",
            "criteria": [
                _criterion(
                    "REGRESSION-01",
                    "Home Assistant Ingress",
                    "CSS, JS, navigation and API requests work through the Supervisor Ingress prefix on every product surface.",
                    ["Open every surface from Home Assistant.", "Navigate without hard refresh errors.", "Exercise a write action such as Start/Resume."],
                    source="Ingress URL contract",
                    route="/",
                    automated_check="Ingress path integration tests",
                ),
                _criterion(
                    "REGRESSION-02",
                    "Restart and resume",
                    "Restart/reload preserves the active workout draft and does not lose completed evidence.",
                    ["Start a workout.", "Reload/restart the add-on as permitted.", "Resume and verify saved state."],
                    source="Release gate",
                    route="/workout",
                    automated_check="full training journey tests",
                ),
                _criterion(
                    "REGRESSION-03",
                    "History and Pep export",
                    "Completed workout history remains correct and Pep export uses the canonical effective workout event without exposing IDs in the UI.",
                    ["Complete a controlled workout.", "Review Progress/history.", "Verify export contract evidence."],
                    source="Workout evidence + Pep export contract",
                    route="/progress",
                    automated_check="history/export E2E tests",
                ),
                _criterion(
                    "REGRESSION-04",
                    "Approved-content boundary",
                    "The app does not fabricate Weeks 2–52, unapproved progression targets or person-specific loads.",
                    ["Review available programme content.", "Check unapproved person profile behaviour.", "Check progression suggestions."],
                    source="Programme-authority contract",
                    route="/",
                    automated_check="Week 1 import and no-fabrication tests",
                ),
                _criterion(
                    "REGRESSION-05",
                    "Responsive/touch acceptance",
                    "Core training actions remain usable with approximately 44px+ touch targets across phone, tablet and desktop.",
                    ["Review the responsive pack.", "Exercise primary controls on a phone-sized viewport."],
                    source="Product accessibility/touch contract",
                    route="/",
                    automated_check="responsive touch tests",
                ),
                _criterion(
                    "REGRESSION-06",
                    "Production image verification",
                    "Exact-main CI passes and public amd64/aarch64 production images are published and anonymously pullable before a live update.",
                    ["Check release workflow for the exact merged main SHA.", "Confirm both architecture builds and public-image verification pass."],
                    source="Getfit release workflow",
                    route="/settings",
                    viewports=["desktop"],
                    automated_check="GitHub CI + Release workflow",
                ),
            ],
        },
    ],
}


def acceptance_spec_payload() -> dict[str, Any]:
    """Return the immutable versioned acceptance specification."""

    return ACCEPTANCE_SPEC
